version: "3.9"
services:

  #######################################
  # Postgres database
  #######################################
  db:
    image: postgres:9.6 # For run local
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-kong}"
      POSTGRES_DB: "${POSTGRES_DB:-kong}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-kong}"
    ports:
      - 5432:5432
    networks:
      - kongnw

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong:2.8.1
    restart: on-failure
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "${POSTGRES_HOST:-db}"
      KONG_PG_DATABASE: "${POSTGRES_DB:-kong}"
      KONG_PG_USER: "${POSTGRES_USER:-kong}"
      KONG_PG_PASSWORD: "${POSTGRES_PASSWORD:-kong}"
    networks:
      - kongnw

  #######################################
  # MyKong: The API Gateway
  #######################################
  kong:
    build:
      context: .
      args:
        kong_env: local
    restart: on-failure
    environment:
      KONG_DATABASE: "${KONG_DATABASE_MODE:-postgres}"
      KONG_ADMIN_LISTEN: 0.0.0.0:${KONG_ADMIN_PORT:-8001}
      # DB-Less mode - close comment line 49 for kong db-less mode
      # KONG_DECLARATIVE_CONFIG: /home/kong/kong.yml
      # DB-Mode - comment line 51 - 54 for kong db-less mode
      KONG_PG_HOST: "${POSTGRES_HOST:-db}"
      KONG_PG_DATABASE: "${POSTGRES_DB:-kong}"
      KONG_PG_USER: "${POSTGRES_USER:-kong}"
      KONG_PG_PASSWORD: "${POSTGRES_PASSWORD:-kong}"
    depends_on:
      - db
    ports:
      - 8000:8000
      - 8001:8001
    networks:
      - kongnw

  #######################################
  # Internal mock microservices
  #######################################
  web:
    image: nginx
    volumes:
      - ./.conf/nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - 8080
      - 8081
    networks:
      - kongnw
  
  #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    image: pantsel/konga:0.14.9
    command: "-c prepare -a postgres -u postgresql://${POSTGRES_USER:-kong}:${POSTGRES_PASSWORD:-kong}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${KONGA_DB:-konga}"
    networks:
      - kongnw
    restart: on-failure

  #######################################
  # Konga database prepare
  #######################################
  konga:
    image: pantsel/konga:0.14.9
    environment:
      DB_ADAPTER: postgres
      DB_URI: postgresql://${POSTGRES_USER:-kong}:${POSTGRES_PASSWORD:-kong}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${KONGA_DB:-konga}
      NODE_ENV: production
    ports:
      - 1337:1337
    networks:
      - kongnw
    restart: always
    depends_on:
      - db

networks:
  kongnw: {}